server_names_hash_bucket_size 64;
map_hash_bucket_size 512;
variables_hash_max_size 2048;

proxy_buffer_size   128k;
proxy_buffers   4 256k;
proxy_busy_buffers_size   256k;

include /etc/nginx/includes/gzip.conf;

include /etc/nginx/sites/maps/*.conf;

include /etc/nginx/sites/*.conf;
